### ISSUE TITLE
Running crashed due to ""IndexError: list index out of range"

### ISSUE THREAD

**Issue by lisalamberte** [gbouras13/pharokka#235]
* phrokka version: v1.2.0
* Python version: Python 3.10.8
* Operating System: Linux

### Description

I was trying to run pharokka, but it crashed due to "IndexError: list index out of range". What should I do to remedy this? 

### What I Did

Command: pharokka.py -i 234389_PhageGq1.fna -o phage_gq1 -t 4

Traceback (most recent call last):
  File "/home/ubuntu/lisa-armyVol3/miniconda3/envs/phage/bin/pharokka.py", line 87, in <module>
    input_commands.check_dependencies(logger)
  File "/home/ubuntu/lisa-armyVol3/miniconda3/envs/phage/bin/input_commands.py", line 313, in check_dependencies
    mash_version = version_line[0].split(' ')[2]
IndexError: list index out of range

**Comment by gbouras13** [comment]
Hi @lisa-maiya, it looks like there’s an issue with your mash installation. Other users have reported similar mash issues that were caused by gsl not being installed. You can fix this by installing gsl in your environment e.g. 

conda install -c conda-forge gsl

(See https://anaconda.org/conda-forge/gsl) 

Then trying pharokka again.

Please let me know if that doesn’t work!

George

**Comment by lisa-maiya** [comment]
Hi George,

I have installed gsl in my environment, but unfortunately I still get exactly the same error.

Traceback (most recent call last):
  File "/home/ubuntu/lisa-armyVol3/miniconda3/envs/pharokkaENV/bin/pharokka.py", line 87, in <module>
    input_commands.check_dependencies(logger)
  File "/home/ubuntu/lisa-armyVol3/miniconda3/envs/pharokkaENV/bin/input_commands.py", line 313, in check_dependencies
    mash_version = version_line[0].split(' ')[2]
IndexError: list index out of range

**Comment by gbouras13** [comment]
Hi Lisa,

Would be able to run:

mash help

or 

mash --version 

and post what the output is? 

George

**Comment by lisa-maiya** [comment]
Sure!

I get this:

mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

**Comment by gbouras13** [comment]
Hi Lisa,

it does seem like a gsl issue - frustrating that just installing it didn’t work. Perhaps try creating a new conda environment with both gsl and pharokka at the beginning and perhaps that will work? Something like:

conda create -n pharokkanew pharokka gsl

and that may work

**Comment by gbouras13** [comment]
Actually based on that thread, first try

conda install -c conda-forge gsl=2.7=he838d99_0

George

**Comment by gbouras13** [comment]
And if all of that fails, maybe try:

conda create -n pharokkanew pharokka mash==2.2

**Comment by lisa-maiya** [comment]
HI George, 

I have done both, but still came up with this:

 Traceback (most recent call last):
  File "/home/ubuntu/lisa-armyVol3/miniconda3/envs/pharokkanew/bin/pharokka.py", line 5, in <module>
    import processes
  File "/home/ubuntu/lisa-armyVol3/miniconda3/envs/pharokkanew/bin/processes.py", line 8, in <module>
    from BCBio import GFF
ModuleNotFoundError: No module named 'BCBio'

I've tried to install BCBio via conda but it comes up with this: 

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - bcbio-nextgen -> python[version='2.7.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.23=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__glibc==2.23=0
  - feature:|@/linux-64::__unix==0=0
  - bcbio-nextgen -> click -> __win
  - bcbio-nextgen -> sh -> __unix

Your installed version is: 0

**Comment by gbouras13** [comment]
Hi Lisa,

That is so strange, I don't understand why bcbio-gff wouldn't install with pharokka as it's an encoded conda dependency for pharokka. From my experience, that sort of error (with glibc) are due to something obscure failing in your overall conda build, maybe like your channels. So perhaps re-doing the channels in the usual order:

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge

could work.

Also, maybe try creating an environment with bcbio-gff at the start:

conda create -n pharokkanew pharokka mash==2.2 bcbio-gff

The other thing to try is to use mamba if you can install it - those glibc sort of problems often go away with mamba.

George

**Comment by lisa-maiya** [comment]
Hi George, 

That definitely did it! I've managed to run pharokka successfully now. Thank you so much for taking the time and patience to answer my queries!

All the best 
Lisa

**Comment by gbouras13** [comment]
No problem Lisa! Let me know if you have any other problems. 

I'm going to leave the issue open for anyone with a similar error, as a few other users have had issues. 

George

**Comment by gjordaopiedade** [comment]
for others having a similar error message but with tRNAscan-SE
Check for conflicting PERL libraries 
try:
`export PERL5LIB=`

**Comment by gbouras13** [comment]
@gjordaopiedade thanks for this - if you can (you've probably fixed it by now!), would you able share some more details about any errors you had? 

George

**Comment by gbouras13** [comment]
Much appreciated @gjordaopiedade. This will be helpful in case anyone else runs into the same error.

George

**Comment by Taiwomercy** [comment]
I have installed pharokka into one of my directories on hpc using the following from the installation instructions:

git clone https://github.com/gbouras13/pharokka.git
cd pharokka
conda env create -f environment.yml
conda activate pharokka_env

./bin/install_databases.py -h
./bin/pharokka.py -h

I ran pharokka and I got this error:

Checking database installation.
All databases have been successfully checked.
Checking dependencies.
Phanotate not found. Please reinstall pharokka.
Starting pharokka v1.2.1

What other way can I try to install pharokka to ensure phanotate works?

**Comment by gbouras13** [comment]
Hi @Taiwomercy,

It seems like your dependencies did not install.

I would try a bioconda install 

```
conda create -n pharokkaENV pharokka
conda activate pharokkaENV
pharokka.py -h
```

rather than a manual installation. 

Alternatively, if only phanotate is missing, you can try 

```
conda install phanotate
```

which should install it.

George

**Comment by Taiwomercy** [comment]
Hi, I am trying to specify that pharokka predict my genes with prodigal and not phanotate, everything works fine when I did not specify -g prodigal but I keep getting error when I specify prodigal as the gene predictor.

Here is the command:

pharokka.py -i /users/PDS0325/taiwomercy/AzotobacterPhages_Sequencing/data/short_reads/Fasta/Vincere.fas
ta -o /users/PDS0325/taiwomercy/AzotobacterPhages_Sequencing/data/processed_v2/Pharokka_annotate/vincere_short_pharokprodgal -d /users/PDS0325/taiwomercy/bio
informatics_tools/pharokka/ -g prodigal -t 8

Here is the error:

Traceback (most recent call last):
  File "/users/PDS0325/taiwomercy/bioinformatics_tools/miniconda3/envs/pharokkaENV/bin/pharokka.py", line 447, in <module>
    main()
  File "/users/PDS0325/taiwomercy/bioinformatics_tools/miniconda3/envs/pharokkaENV/bin/pharokka.py", line 278, in main
    run_pyrodigal(input_fasta, out_dir, args.meta, args.coding_table)
  File "/users/PDS0325/taiwomercy/bioinformatics_tools/miniconda3/envs/pharokkaENV/bin/processes.py", line 276, in run_pyrodigal
    orf_finder = pyrodigal.OrfFinder(meta=prodigal_metamode)
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'
(pharokkaENV) [taiwomercy@owens-login04 miniconda3]$

**Comment by gbouras13** [comment]
Hi @Taiwomercy,

I have made a new issue for the problem. You can see my response here https://github.com/gbouras13/pharokka/issues/297. Thanks for raising it. I'm also closing this issue.

George

**Comment by PortugueseMaestro** [comment]
> export PERL5LIB=

Thank you. I was getting same error:

trna_version = version_line[0].split(" ")[1]
IndexError: list index out of range

Running export **PERL5LIB=** solved my problem when updating Pharokka to v1.5.0.
